<?php

namespace Tests\Feature\Roles;

use Tests;
use Tests\TestCase;
use App\Models\User;

class RoleTest extends TestCase
{



    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate:refresh', [
            // this is a connection name, not a database name!!!
            '--force'    => true,
            '--seed'    => true,
        ]);

    }

    public function testCanAssignRoleToUser()
    {
        $user = factory(User::class)->create();
        $user->assignRole('admin');
        $this->assertTrue($user->hasRole('admin'));
    }

    public function testAdminPermissions()
    {
        $user = factory(User::class)->create();
        $user->assignRole('admin');
        $this->assertTrue($user->can('create user'));
        $this->assertTrue($user->can('edit user'));
        $this->assertTrue($user->can('delete user'));
    }

    public function testUserCantPermissions()
    {
        $user = factory(User::class)->create();
      //  $user->assignRole('admin');
        $this->assertFalse($user->can('create user'));
        $this->assertFalse($user->can('edit user'));
        $this->assertFalse($user->can('delete user'));
    }


}
